Validate names in heroku recipe do not exceed the name limit
platanus/potassium pull request #344
Opened 2021-02-19 17:00 UTC by agomezcampero

**Description**
Closes #331 

When the default app name or default pipeline name exceeds 30 characters (the limit set by Heroku), the user is prompted to input a new name. This name doesn't have to include either the name prefix or the environment name at the end (should we should enforce that?).

Heroku app names are now set during the ask section of the recipe. This is because it doesn't make sense to ask a user for a Heroku app name if they don't want to deploy the app.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +    puts "Remember to connect the github repository to the new pipeline"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +    puts "run #{open_pipeline_command} to open the dashboard"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +    puts "You are not logged in into heroku"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +    puts "Run #{login_command} and enter your credentials"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +    puts "You can install the heroku recipe again to create the app in heroku"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +    puts "Just run #{install_command}"
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 17:00 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +      puts "Heroku names must be shorter than #{HEROKU_NAMES_MAX_CHARS} chars."
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-02-19 18:07 UTC, difernandez requested changes
Regarding if we should enforce prefix/suffix, for prefix I don't think is really necessary. For suffix I'm not sure how we should handle it, cause we have `heroku-stage` that relies on the suffix convention and it's used in mailer and sentry configs. Maybe it's not so bad to not enforce it if we add a warning before the name ask, something like:

> Note that potassium projects use the gem "heroku-stage" for some configurations. If your name doesn't follow a certain convention, some things might not work as intended. Here's the convention: https://github.com/platanus/heroku-stage#the-convention

A little long but, something like that. What do you think?

Other than that it looks good! Could you add an entry to the Changelog for this feature (or fix?) pls?

2021-02-19 18:17 UTC, agomezcampero commented
> https://github.com/platanus/heroku-stage#the-convention

2021-02-19 18:21 UTC, agomezcampero commented
> Regarding if we should enforce prefix/suffix, for prefix I don't think is really necessary. For suffix I'm not sure how we should handle it, cause we have `heroku-stage` that relies on the suffix convention and it's used in mailer and sentry configs. Maybe it's not so bad to not enforce it if we add a warning before the name ask, something like:
> 
> > Note that potassium projects use the gem "heroku-stage" for some configurations. If your name doesn't follow a certain convention, some things might not work as intended. Here's the convention: https://github.com/platanus/heroku-stage#the-convention
> 
> A little long but, something like that. What do you think?
> 
> Other than that it looks good! Could you add an entry to the Changelog for this feature (or fix?) pls?

Considering that we are using "heroku-stage" I would definitely enforce the naming convention. I think the downside of some things not working is a lot higher than having to choose a slightly shorter name. I'll add this to the pr and add the entry to the Changelog.

2021-02-26 13:37 UTC, monkeyci commented on lib/potassium/recipes/heroku.rb
> +        puts "Potassium uses the heroku-stage gem, because of that '#{suffix}' will be "\
**[rubocop]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Rails/Output: Do not write to stdout. Use Rails's logger if you want to log.

2021-03-01 12:21 UTC, difernandez approved these changes

2021-03-01 12:22 UTC, merged