Feat/webpacker addons
platanus/potassium pull request #350
Opened 2021-04-16 20:49 UTC by gmq

Makes the necessary changes to use activeadmin in webpacker mode:

- Removes Active Skin
- Forces tailwind 1.9.6 since the default install breaks. #349 covers the update to v2
- Moves the installation of activeadmin to after the webpacker install has run.
- Webpacker (and the frontend section) always runs.

Shouldn't be merged until a new version of activeadmin_addons has been released.

![chrome_USK5WUhw6r](https://user-images.githubusercontent.com/472791/115082256-9c26ab00-9ed3-11eb-8025-511d3fca8e42.png)

2021-04-22 15:38 UTC, ldlsegovia requested changes
Ojo que falló CI

2021-04-22 15:38 UTC, ldlsegovia commented on lib/potassium/recipes/front_end.rb
> +      run "rails webpacker:install:#{value}" unless [:none, :None].include? get(:front_end).to_sym
podrías usar `value.to_sym`

2021-04-22 15:38 UTC, ldlsegovia commented on lib/potassium/recipes/front_end.rb
> +    run 'bin/yarn add tailwindcss@1.9.6'
Agregaría la versión acá https://github.com/platanus/potassium/blob/master/lib/potassium/version.rb#L9

2021-04-23 14:51 UTC, ldlsegovia approved these changes

2021-04-23 16:01 UTC, rjherrera reviewed
una duda, estaba mirando active skin y es un css relativamente simple y poco más, ahora con todo webpackerizado, cuál sería la forma de agregarlo a un proyecto "a mano", pensando en no usar la gema pero "incorporarla" en potassium?

2021-04-23 16:02 UTC, gmq commented on lib/potassium/version.rb
> +  TAILWINDCSS = "1.9.6"
Es incompatible con webpacker < 6, hay que usar una versión con backward compatibility (#349)

2021-04-23 16:03 UTC, rjherrera commented on lib/potassium/version.rb
> +  TAILWINDCSS = "1.9.6"
lo habías dicho en la descripción sorry jaja

2021-04-23 16:04 UTC, gmq commented
> una duda, estaba mirando active skin y es un css relativamente simple y poco más, ahora con todo webpackerizado, cuál sería la forma de agregarlo a un proyecto "a mano", pensando en no usar la gema pero "incorporarla" en potassium?

De poder se puede (importando el scss) pero me da cosa agregar CSS al repo que no hicimos nosotros y que hay que mantener después.

2021-04-23 16:17 UTC, gmq commented
Estuve buscando themes y https://www.npmjs.com/package/arctic_admin es el único que tiene soporte para AA webpack (o sea, tiene un paquete en npm)

2021-05-07 21:07 UTC, gmq commented
Agregué Arctic Admin
![image](https://user-images.githubusercontent.com/472791/117508486-a8dc7300-af56-11eb-9ebf-3dd3512878bb.png)

2021-05-10 15:27 UTC, rjherrera approved these changes

2021-06-25 19:19 UTC, ldlsegovia commented on lib/potassium/recipes/admin.rb
> +        "@import \"~@activeadmin/activeadmin/src/scss/mixins\";\n" +
@gmq `@import \"~@activeadmin/activeadmin/src/scss/mixins\";\n` y `@import \"~@activeadmin/activeadmin/src/scss/base\";` se borran verdad? si no es así, hay que sacarlas para que funcione bien

2021-06-25 22:23 UTC, ldlsegovia commented
@gmq instalé en un proyecto rails desde cero active admin, addons y arctic_admin y funcionó bien. Saqué release de addons, ya estaría de mi lado lo que faltaba. https://github.com/platanus/webpack-addons-test
https://rubygems.org/gems/activeadmin_addons/versions/1.8.0

2021-07-01 15:13 UTC, gmq commented on lib/potassium/recipes/admin.rb
> +        "@import \"~@activeadmin/activeadmin/src/scss/mixins\";\n" +
Se borran, arctic_admin incluye todo.

2021-07-01 15:51 UTC, merged