Rails 7 & Vite
platanus/potassium pull request #431
Opened 2023-02-23 19:54 UTC by gmq

Actualiza Potassium para que instale Rails 7, reemplazando Webpacker por Vite.

Hay varias alternativas para reemplazar Webpacker/Shakpacker (propshaft, jsbundling-rails, etc) pero me incliné por `vite-ruby` por ser Vite la opción oficial para Vue. Un problema que siempre teniamos con webpacker es que como es super específico de Rails, era complicado encontrar soluciones a los problemas que nos encontramos, mientras que si se busca Vue en internet, se asume que se está usando Vite.

Aparte de eso, al ser un wrapper es esbuild, Vite es _súper_ rápido y además trae casi todo configurado por defecto. Ya no es necesario agregar loaders, la configuración para vue es una linea, etc.

Detalle
El último commit agrega un paso para hacer build del package de npm de addons, ya que aun no se mergea. Una vez que esté lo de addons se puede eliminar.

2023-03-01 15:48 UTC, difernandez reviewed
Dejo algunos comentarios! Voy a probarlo también después y vuelvo si ahí me sale algún detalle

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/front_end_vite.rb
> +    run "yarn add --dev #{DEPENDENCIES[:tailwind].join(' ')}"
esto no debería ser con `--dev` creo

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/front_end_vite.rb
> -      "eslint-plugin-tailwindcss"
Por qué sacar este? No debería ir en un `tailwind_dev`?

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/admin.rb
> +      run 'rmdir app/javascript'
esto no sería lo mismo que `rm -rf app/javascript`?

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/admin.rb
> +        ActiveAdmin::Views::Pages::Base.include ActiveAdminViteJS
no debería ser `prepend` en vez de `include`? Por lo que entiendo, `prepend` hace que sea este módulo lo primero que se revisa al momento de buscar un método usado

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/admin.rb
> +        ActiveSupport.on_load(:action_view) { include ActiveAdminViteJS }
Por qué es necesario esto?

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/google_tag_manager.rb
> +      # policy.connect_src(
por qué se comenta? Por si hay algo en particular que molesta y alguien migra a esto, para tenerlo en cuenta

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/cleanup.rb
> +    # cut_comments "config/initializers/backtrace_silencers.rb", limit: 100
esto se pasó?

2023-03-01 15:48 UTC, difernandez commented on spec/front_end_vite_spec.rb
> +  context 'with vue' do
quizás sacaría este contexto, ya que no hay alternativa ahora. Que quede todo bajo el describe, así también más rápido porque te ahorras un `before` y una creación/destrucción del proyecto

2023-03-01 15:48 UTC, difernandez commented on spec/features/api_spec.rb
> +    expect(gemfile_content).to include("power_api")
na que ver con el PR, pero si rails ocupa siempre comillas dobles quizás nosotros también deberíamos jaja

2023-03-01 15:48 UTC, difernandez commented on lib/potassium/recipes/coverage.rb
> +    run "yarn add jest-text-formatter@1.0.2 c8 --dev"
este paquete sigue funcionando con el output de vitest?

2023-03-01 15:56 UTC, difernandez commented on lib/potassium/recipes/front_end_vite.rb
> +    run "yarn add --dev #{DEPENDENCIES[:typescript].join(' ')}"
ignoraa esto también, cambió a no dev

2023-03-01 16:52 UTC, gmq commented on lib/potassium/recipes/front_end_vite.rb
> -      "eslint-plugin-tailwindcss"
Me faltó re-agregarlo en en `lib/potassium/recipes/style.rb` 😬

2023-03-01 16:53 UTC, gmq commented on lib/potassium/recipes/admin.rb
> +      run 'rmdir app/javascript'
rmdir no borra los directorios si no están vacíos, solo los quiero borrar si es que lo de active_admin es lo único ahí, por si alguna otra cosa agrega archivos

2023-03-01 16:55 UTC, gmq commented on lib/potassium/recipes/google_tag_manager.rb
> +      # policy.connect_src(
Estaba haciendo mucho esta receta, reemplazando todo el CSP y causaba problemas si es que algun puerto o tipo de archivo no coincidía. Prefiero que solo agregue las lineas que le competen y dependa del proyecto si activan las policies más especificas del CSP.

2023-03-01 16:57 UTC, gmq commented on spec/features/api_spec.rb
> +    expect(gemfile_content).to include("power_api")
Eso mismo pensé, creo que en algún momento lo hablamos para activar estas reglas en rubocop (pero era al revés creo, single quotes) pero no encuentro donde.

2023-03-01 17:03 UTC, gmq commented on lib/potassium/recipes/admin.rb
> +        ActiveAdmin::Views::Pages::Base.include ActiveAdminViteJS
Lo saqué de acá 🤔 
https://github.com/activeadmin/activeadmin/issues/7264#issuecomment-1211367990
Voy a probar con prepend

2023-03-01 17:04 UTC, gmq commented on lib/potassium/recipes/admin.rb
> +        ActiveSupport.on_load(:action_view) { include ActiveAdminViteJS }
Honestamente no tengo idea de donde salió, tal vez copilot ganó sentience, la voy a borrar.

2023-03-01 17:47 UTC, difernandez commented on lib/potassium/recipes/admin.rb
> +        ActiveAdmin::Views::Pages::Base.include ActiveAdminViteJS
ah supongo que da lo mismo tonces

2023-03-01 18:53 UTC, difernandez commented on lib/potassium/recipes/front_end.rb
> -    copy_file '../assets/config/webpack/rules/typescript.js', 'config/webpack/rules/typescript.js'
se podría eliminar esta carpeta de los assets ahora

2023-03-01 18:54 UTC, difernandez commented on lib/potassium/recipes/front_end.rb
> -      add_readme_header :webpack
también se podría reemplazar esta entrada del readme por algo que explique si hay que correr algo más aparte del rails server o algo

2023-03-03 13:43 UTC, difernandez approved these changes
💯 🚀

2023-03-04 21:18 UTC, ldlsegovia approved these changes
👏🏻

2023-03-04 21:18 UTC, ldlsegovia commented on lib/potassium/assets/bin/setup.erb
> +yarn install
por qué ya no se usa desde bin/?

2023-03-06 15:21 UTC, gmq commented on lib/potassium/assets/bin/setup.erb
> +yarn install
Shakapacker lo agregaba pero rails-vite no. Igual pareciera que lo único que hace es [revisar si existe](https://github.com/shakacode/shakapacker/blob/master/lib/install/bin/yarn) asi que no se pierde mucho

2023-03-21 12:54 UTC, difernandez requested changes

2023-03-21 12:54 UTC, difernandez commented on lib/potassium/recipes/style.rb
> +        "eslint-plugin-tailwindcss"
falta un espacio antes de esto, se está uniendo al paquete anterior

2023-03-21 14:09 UTC, difernandez approved these changes

2023-03-23 19:11 UTC, merged